'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')

const { renderReport } = require('../src')
const { eventsOfType } = require('./helpers')

// 64 by 64 PNG, generated by test/fixtures/make-fixture.js so no binary blob
// has to be checked in by hand.
const LOGO = path.join(__dirname, 'fixtures', 'logo.png')

test('an image keeps its aspect ratio when only a width is given', async () => {
  const r = await renderReport({
    titleBlock: false,
    blocks: [{ type: 'image', src: LOGO, width: 120 }]
  })

  const img = eventsOfType(r.layout, 'image')[0]
  assert.equal(img.width, 120)
  assert.equal(img.height, 120, 'a square source stays square')
  assert.deepEqual(img.natural, { width: 64, height: 64 })
  assert.equal(img.scaled, false)
})

test('an image derives its width from an explicit height', async () => {
  const r = await renderReport({
    titleBlock: false,
    blocks: [{ type: 'image', src: LOGO, height: 40 }]
  })
  const img = eventsOfType(r.layout, 'image')[0]
  assert.equal(img.height, 40)
  assert.equal(img.width, 40)
})

test('an image is never drawn wider than the text column', async () => {
  const r = await renderReport({
    titleBlock: false,
    blocks: [{ type: 'image', src: LOGO, width: 5000 }]
  })
  const img = eventsOfType(r.layout, 'image')[0]
  assert.ok(img.width <= r.geometry.width + 0.01, `${img.width} fits in ${r.geometry.width}`)
  assert.equal(Math.round(img.height), Math.round(img.width), 'the ratio held while clamping')
})

test('an image taller than a page is scaled down instead of clipped', async () => {
  const r = await renderReport({
    titleBlock: false,
    blocks: [{ type: 'image', src: LOGO, width: 400, height: 4000 }]
  })

  const img = eventsOfType(r.layout, 'image')[0]
  assert.equal(img.scaled, true, 'the scaling was recorded')
  assert.ok(img.height <= r.geometry.capacity + 0.01, 'it fits on a page now')
  assert.equal(r.pages, 1)
})

test('an image moves to the next page whole rather than being split', async () => {
  const probe = await renderReport({ titleBlock: false, blocks: [] })
  const r = await renderReport({
    titleBlock: false,
    blocks: [
      { type: 'spacer', height: probe.geometry.capacity - 40 },
      { type: 'image', src: LOGO, width: 120 }
    ]
  })

  const img = eventsOfType(r.layout, 'image')[0]
  assert.equal(img.page, 2)
  assert.equal(r.pages, 2)
})

test('a heading above an image travels with it', async () => {
  const probe = await renderReport({ titleBlock: false, blocks: [] })
  const r = await renderReport({
    titleBlock: false,
    blocks: [
      { type: 'spacer', height: probe.geometry.capacity - 60 },
      { type: 'heading', level: 2, text: 'Floor plan' },
      { type: 'image', src: LOGO, width: 150 }
    ]
  })

  const heading = eventsOfType(r.layout, 'heading')[0]
  const img = eventsOfType(r.layout, 'image')[0]
  assert.equal(heading.page, 2, 'the heading did not stay behind')
  assert.equal(img.page, 2)
})

test('alignment shifts the image without changing its size', async () => {
  const sizes = []
  for (const align of ['left', 'center', 'right']) {
    const r = await renderReport({
      titleBlock: false,
      blocks: [{ type: 'image', src: LOGO, width: 100, align }]
    })
    const img = eventsOfType(r.layout, 'image')[0]
    sizes.push(`${img.width}x${img.height}`)
  }
  assert.equal(new Set(sizes).size, 1, 'all three alignments drew the same size')
})

test('a caption under an image is counted in the space it needs', async () => {
  const without = await renderReport({ titleBlock: false, blocks: [{ type: 'image', src: LOGO, width: 100 }] })
  const withCaption = await renderReport({
    titleBlock: false,
    blocks: [{ type: 'image', src: LOGO, width: 100, caption: 'Figure 1. The site as measured.' }]
  })

  assert.equal(without.layout.filter(e => e.type === 'image').length, 1)
  assert.equal(withCaption.layout.filter(e => e.type === 'image').length, 1)
  assert.equal(withCaption.pages, 1)
})

test('a Buffer works as a source', async () => {
  const r = await renderReport({
    titleBlock: false,
    blocks: [{ type: 'image', src: fs.readFileSync(LOGO), width: 60 }]
  })
  assert.equal(eventsOfType(r.layout, 'image')[0].width, 60)
})

test('a missing file gives a message that names the file and the supported formats', async () => {
  await assert.rejects(
    () => renderReport({ blocks: [{ type: 'image', src: '/no/such/logo.png' }] }),
    err => {
      assert.match(err.message, /block 0 \(image\)/)
      assert.match(err.message, /\/no\/such\/logo\.png/)
      assert.match(err.message, /PNG and JPEG/)
      return true
    }
  )
})

test('an image without a src is rejected', async () => {
  await assert.rejects(
    () => renderReport({ blocks: [{ type: 'image', width: 100 }] }),
    /needs a src/
  )
})

test('a zero or negative size is rejected instead of drawing nothing', async () => {
  await assert.rejects(
    () => renderReport({ blocks: [{ type: 'image', src: LOGO, width: 0, height: 0 }] }),
    /cannot be rendered/
  )
})
